### ISSUE TITLE
Need HeaderMatchingFilter to match more than one header

### ISSUE THREAD

**Issue by c-alpha** [afewmail/afew#268]
If I want to have a logical `or` of more than one header, I can simply write several filters, which all set the same tags.

But there is currently no way (or at least I couldn't figure one out) to have a logical `and` of two or more header fields to match a filter?

**Comment by GuillaumeSeren** [comment]
Hello @c-alpha ,
no I don't think it is covered use case actually.

Maybe it could be an upgrade or a new filter, I am curious about the use case behind this need.

Beside that, how do you see such configuration ?

**Comment by c-alpha** [comment]
> Maybe it could be an upgrade or a new filter, I am curious about the use case behind this need.

The use-case is "creative use" of mailing lists, where (part of) the List-ID changes from time to time. I presume this is to deter email address harvesters.

> Beside that, how do you see such configuration ?

With the current syntax it would probably have to be implicit:
```ini
[HeaderMatchingFilter.7]
message = 'Tagging mailing lists (foobar)'
tags = +lst/foobar;-new
header = To
pattern = john.doe@example.com
header = List-Id
pattern = <.*\.list.fuddler>
header = Subject
pattern = ^\[foobar\].*
```
I.e. to interpret `header` and `pattern` as tuples, and to allow more than one tuple. For the filter to match, all tuples must match.

Another - admittedly far fetched, but IMHO more elegant - approach would be to use [TOML](https://github.com/toml-lang/toml) ([python binding](https://github.com/sdispater/tomlkit)) for the config file:
```toml
[HeaderMatchingFilter]

	[HeaderMatchingFilter.foobar-list]
	message = 'Tagging mailing lists (foobar)'
	tags = [ '+lst/foobar', '-new' ]
	[[HeaderMatchingFilter.foobar-list.matching]]
	header = 'To'
	pattern = 'john.doe@example.com'
	[[HeaderMatchingFilter.foobar-list.matching]]
	header = 'List-Id'
	pattern = '<.*\.list.fuddler>'
	[[HeaderMatchingFilter.foobar-list.matching]]
	header = 'Subject'
	pattern = '^\[foobar\]'
```

Which in JSON-land would be:
```json
{
   "HeaderMatchingFilter" : {
      "foobar-list" : {
         "matching" : [
            {
               "pattern" : "john.doe@example.com",
               "header" : "To"
            },
            {
               "header" : "List-Id",
               "pattern" : "<.*\\.list.fuddler>"
            },
            {
               "header" : "Subject",
               "pattern" : "^\\[foobar\\]"
            }
         ],
         "message" : "Tagging mailing lists (foobar)",
         "tags" : [
            "+lst/foobar",
            "-new"
         ]
      }
   }
}
```
I.e. a new property `matching`, which is an array of `header`/`pattern` pairs. For the filter to match, all elements of `matching` must match.

This would also remove the need to juggle the array indices by hand. 😉
